rvm:
  - 1.8.7
  - 1.9.3
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
before_install:
  - git clone https://github.com/sstephenson/sprockets.git ../sprockets
